/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import bean.Perfume;
import bean.Cliente;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import dao.ClienteDAO;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Eduardo Barbosa
 */
public class Tela_Cliente extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Cliente
     */
    DefaultTableModel dtm_tabela;
    ArrayList <Cliente> listaCliente;
    ClienteDAO pd_operacoes;
    public Tela_Cliente() {
        initComponents();
        //configuração tabela 
        dtm_tabela = new DefaultTableModel(null, new String[]{"cpf","nome","telefone","endereco","insta","facebook","cartao","pix"});
        
        try {
            pd_operacoes = new ClienteDAO();
        } catch (SQLException | ClassNotFoundException ex) {
            System.out.println("\n Erro ao conectar: "+ex.toString());
        }
        
        // Atualização da tabela para preservar a integridade do sistema.
        try {
            atualizaTabela();
        } catch (SQLException ex) {
            System.out.print("SQLException: "+ex.toString());
        } catch (ClassNotFoundException ex) {
            System.out.print("ClassNotFoundException: "+ex.toString());
        }
        
    }
    private void atualizaTabela() throws SQLException, ClassNotFoundException
    {
        jtb_cliente.setModel(dtm_tabela);
        dtm_tabela.setNumRows(0);
        listaCliente = pd_operacoes.buscarListaCompleta_cliente();
        for (Cliente p : listaCliente) 
        {
            dtm_tabela.addRow(new Object[]{p.getCpf(),p.getNome(),p.getTelefone(),p.getEndereco(),p.getEnd_insta(),p.getEnd_face(),p.getCartaoDeCredito(),p.getPix()});
	}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jlb_cpf = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jta_cpf = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtb_cliente = new javax.swing.JTable();
        jlb_nome = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jta_nome = new javax.swing.JTextArea();
        jlb_telefone = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jta_telefone = new javax.swing.JTextArea();
        jlb_endereco = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jta_endereco = new javax.swing.JTextArea();
        jlb_end_insta = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jta_end_insta = new javax.swing.JTextArea();
        jlb_end_face = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jta_end_face = new javax.swing.JTextArea();
        jlb_cartaoDeCredito = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jta_cartaoDeCredito = new javax.swing.JTextArea();
        jlb_pix = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        jta_pix = new javax.swing.JTextArea();
        jbt_inserirCliente = new javax.swing.JButton();
        jbt_salvarPdfCliente = new javax.swing.JButton();
        jbt_salvarTxtCliente = new javax.swing.JButton();
        jbt_atualizarCliente = new javax.swing.JButton();
        jbt_deletarCliente = new javax.swing.JButton();

        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jScrollPane6.setViewportView(jTextArea5);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jlb_cpf.setText("cpf:");

        jta_cpf.setColumns(20);
        jta_cpf.setRows(5);
        jta_cpf.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(jta_cpf);

        jtb_cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jtb_cliente);

        jlb_nome.setText("nome:");

        jta_nome.setColumns(20);
        jta_nome.setRows(5);
        jScrollPane3.setViewportView(jta_nome);

        jlb_telefone.setText("telofone:");

        jta_telefone.setColumns(20);
        jta_telefone.setRows(5);
        jScrollPane4.setViewportView(jta_telefone);

        jlb_endereco.setText("endereço:");

        jta_endereco.setColumns(20);
        jta_endereco.setRows(5);
        jScrollPane5.setViewportView(jta_endereco);

        jlb_end_insta.setText("endereço do Instagram:");

        jta_end_insta.setColumns(20);
        jta_end_insta.setRows(5);
        jScrollPane7.setViewportView(jta_end_insta);

        jlb_end_face.setText("endereço do Facebook:");

        jta_end_face.setColumns(20);
        jta_end_face.setRows(5);
        jScrollPane8.setViewportView(jta_end_face);

        jlb_cartaoDeCredito.setText("cartão de crédito:");

        jta_cartaoDeCredito.setColumns(20);
        jta_cartaoDeCredito.setRows(5);
        jScrollPane9.setViewportView(jta_cartaoDeCredito);

        jlb_pix.setText("pix:");

        jta_pix.setColumns(20);
        jta_pix.setRows(5);
        jScrollPane10.setViewportView(jta_pix);

        jbt_inserirCliente.setText("Inserir");
        jbt_inserirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_inserirClienteActionPerformed(evt);
            }
        });

        jbt_salvarPdfCliente.setText("Salvar em PDF");
        jbt_salvarPdfCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_salvarPdfClienteActionPerformed(evt);
            }
        });

        jbt_salvarTxtCliente.setText("Salvar em TXT");

        jbt_atualizarCliente.setText("Atualizar");
        jbt_atualizarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_atualizarClienteActionPerformed(evt);
            }
        });

        jbt_deletarCliente.setText("Deletar");
        jbt_deletarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_deletarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlb_cartaoDeCredito)
                                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlb_pix))
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jbt_deletarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbt_inserirCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(97, 97, 97)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jbt_salvarPdfCliente)
                                    .addComponent(jbt_salvarTxtCliente)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(47, 47, 47))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlb_end_face)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlb_cpf)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlb_nome)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlb_telefone)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlb_endereco)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlb_end_insta)
                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(156, 156, 156)
                                .addComponent(jbt_atualizarCliente)))
                        .addContainerGap(11, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlb_cpf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlb_nome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlb_telefone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlb_endereco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlb_end_insta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlb_end_face)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbt_atualizarCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_cartaoDeCredito)
                    .addComponent(jbt_deletarCliente)
                    .addComponent(jbt_salvarTxtCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_pix)
                    .addComponent(jbt_salvarPdfCliente)
                    .addComponent(jbt_inserirCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limpartela()
    {
        jta_cpf.setText("");
        jta_nome.setText("");
        jta_telefone.setText("");
        jta_endereco.setText("");
        jta_end_insta.setText("");
        jta_end_face.setText("");
        jta_cartaoDeCredito.setText("");
        jta_pix.setText("");
    }
    private void jbt_inserirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_inserirClienteActionPerformed
        // TODO add your handling code here:
        Cliente c = new Cliente();
        c.setCpf(jta_cpf.getText());
        c.setNome(jta_nome.getText());
        c.setTelefone(jta_telefone.getText());
        c.setEndereco(jta_endereco.getText());
        c.setEnd_insta(jta_end_insta.getText());
        c.setEnd_face(jta_end_face.getText());
        c.setCartaoDeCredito(jta_cartaoDeCredito.getText());
        c.setPix(jta_pix.getText());
        pd_operacoes.adicionarCliente(c);
        
        limpartela();
        // Atualização da tabela para preservar a integridade do sistema.
        try {
            atualizaTabela();
        } catch (SQLException ex) {
            System.out.print("SQLException: "+ex.toString());
        } catch (ClassNotFoundException ex) {
            System.out.print("ClassNotFoundException: "+ex.toString());
        }
    }//GEN-LAST:event_jbt_inserirClienteActionPerformed

    private void jbt_atualizarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_atualizarClienteActionPerformed
        // TODO add your handling code here:
        Cliente c = new Cliente();
        c.setCpf(jta_cpf.getText());
        c.setNome(jta_nome.getText());
        c.setTelefone(jta_telefone.getText());
        c.setEndereco(jta_endereco.getText());
        c.setEnd_insta(jta_end_insta.getText());
        c.setEnd_face(jta_end_face.getText());
        c.setCartaoDeCredito(jta_cartaoDeCredito.getText());
        c.setPix(jta_pix.getText());
        pd_operacoes.alterarCliente(c);
        
        limpartela();
        // Atualização da tabela para preservar a integridade do sistema.
        try {
            atualizaTabela();
        } catch (SQLException ex) {
            System.out.print("SQLException: "+ex.toString());
        } catch (ClassNotFoundException ex) {
            System.out.print("ClassNotFoundException: "+ex.toString());
        }
    }//GEN-LAST:event_jbt_atualizarClienteActionPerformed

    private void jbt_deletarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_deletarClienteActionPerformed
        // TODO add your handling code here:
        pd_operacoes.removerCliente(jta_cpf.getText());
        limpartela();
        
      try {
            atualizaTabela();
        } catch (SQLException ex) {
            System.out.print("SQLException: "+ex.toString());
        } catch (ClassNotFoundException ex) {
            System.out.print("ClassNotFoundException: "+ex.toString());
        }
    }//GEN-LAST:event_jbt_deletarClienteActionPerformed

    private void jbt_salvarPdfClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_salvarPdfClienteActionPerformed
        // TODO add your handling code here:
        Document documento = new Document();
        PdfPTable pdft_tabela = new PdfPTable(8);
        listaCliente = pd_operacoes.buscarListaCompleta_cliente();
        for (Cliente p : listaCliente) 
        {
            
            pdft_tabela.addCell(p.getCpf());
            pdft_tabela.addCell(p.getNome());
            pdft_tabela.addCell(p.getTelefone());
            pdft_tabela.addCell(p.getEndereco());
            pdft_tabela.addCell(p.getEnd_insta());
            pdft_tabela.addCell(p.getEnd_face());
            pdft_tabela.addCell(p.getCartaoDeCredito());
            pdft_tabela.addCell(p.getPix());
            
	}
        try {
            PdfWriter.getInstance(documento, new FileOutputStream("Relatorio_Tabela_Clientes.pdf"));
            documento.open();
            documento.add(new Paragraph(" "));
            documento.add(pdft_tabela);
            System.out.print("\n PDF criado com sucesso.");
            JOptionPane.showMessageDialog(null, "PDF criado com sucesso.");
        } catch (DocumentException | FileNotFoundException ex  ) {
            System.out.print("\n Erro: "+ex.toString());
        }
        documento.close();
    }//GEN-LAST:event_jbt_salvarPdfClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JButton jbt_atualizarCliente;
    private javax.swing.JButton jbt_deletarCliente;
    private javax.swing.JButton jbt_inserirCliente;
    private javax.swing.JButton jbt_salvarPdfCliente;
    private javax.swing.JButton jbt_salvarTxtCliente;
    private javax.swing.JLabel jlb_cartaoDeCredito;
    private javax.swing.JLabel jlb_cpf;
    private javax.swing.JLabel jlb_end_face;
    private javax.swing.JLabel jlb_end_insta;
    private javax.swing.JLabel jlb_endereco;
    private javax.swing.JLabel jlb_nome;
    private javax.swing.JLabel jlb_pix;
    private javax.swing.JLabel jlb_telefone;
    private javax.swing.JTextArea jta_cartaoDeCredito;
    private javax.swing.JTextArea jta_cpf;
    private javax.swing.JTextArea jta_end_face;
    private javax.swing.JTextArea jta_end_insta;
    private javax.swing.JTextArea jta_endereco;
    private javax.swing.JTextArea jta_nome;
    private javax.swing.JTextArea jta_pix;
    private javax.swing.JTextArea jta_telefone;
    private javax.swing.JTable jtb_cliente;
    // End of variables declaration//GEN-END:variables
}
