/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import bean.Cliente;
import bean.Pedido;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import dao.PedidoDAO;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Duduzada
 */
public class Tela_Pedido extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Pedido
     */
    DefaultTableModel dtm_tabela;
    ArrayList <Pedido> listaPedido;
    PedidoDAO pd_operacoes;
    public Tela_Pedido() {
        initComponents();
        
        //configuração tabela 
        dtm_tabela = new DefaultTableModel(null, new String[]{"id ","cpf","pedido","entrega"});
        
        try {
            pd_operacoes = new PedidoDAO();
        } catch (SQLException | ClassNotFoundException ex) {
            System.out.println("\n Erro ao conectar: "+ex.toString());
        }
        
        // Atualização da tabela para preservar a integridade do sistema.
        try {
            atualizaTabela();
        } catch (SQLException ex) {
            System.out.print("SQLException: "+ex.toString());
        } catch (ClassNotFoundException ex) {
            System.out.print("ClassNotFoundException: "+ex.toString());
        }
    }
    
    private void atualizaTabela() throws SQLException, ClassNotFoundException
    {
        jtb_pedido.setModel(dtm_tabela);
        dtm_tabela.setNumRows(0);
        listaPedido = pd_operacoes.buscarListaCompleta_pedido();
        for (Pedido p : listaPedido) 
        {
            dtm_tabela.addRow(new Object[]{p.getId_pedido(),p.getFk_cpf(),p.getDataPedido(),p.getPrazoEntrega()});
	}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlb_id_pedido = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jta_id_pedido = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtb_pedido = new javax.swing.JTable();
        jlb_dataPedido = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jta_dataPedido = new javax.swing.JTextArea();
        jlb_prazoEntrega = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jta_prazoEntrega = new javax.swing.JTextArea();
        jbt_inserirPedido = new javax.swing.JButton();
        jbt_salvarPdfPedido = new javax.swing.JButton();
        jbt_salvarTxtPedido = new javax.swing.JButton();
        jbt_atualizarPedido = new javax.swing.JButton();
        jbt_deletarPedido = new javax.swing.JButton();
        jlb_fk_cpf = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jta_fk_cpf = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jlb_id_pedido.setText("indentificador do pedido:");

        jta_id_pedido.setColumns(20);
        jta_id_pedido.setRows(5);
        jScrollPane1.setViewportView(jta_id_pedido);

        jtb_pedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jtb_pedido);

        jlb_dataPedido.setText("data do pedido:");

        jta_dataPedido.setColumns(20);
        jta_dataPedido.setRows(5);
        jScrollPane3.setViewportView(jta_dataPedido);

        jlb_prazoEntrega.setText("prazo de entrega:");

        jta_prazoEntrega.setColumns(20);
        jta_prazoEntrega.setRows(5);
        jScrollPane4.setViewportView(jta_prazoEntrega);

        jbt_inserirPedido.setText("Inserir");
        jbt_inserirPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_inserirPedidoActionPerformed(evt);
            }
        });

        jbt_salvarPdfPedido.setText("Salvar em PDF");
        jbt_salvarPdfPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_salvarPdfPedidoActionPerformed(evt);
            }
        });

        jbt_salvarTxtPedido.setText("Salvar em TXT");

        jbt_atualizarPedido.setText("Atualizar");
        jbt_atualizarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_atualizarPedidoActionPerformed(evt);
            }
        });

        jbt_deletarPedido.setText("Deletar");
        jbt_deletarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_deletarPedidoActionPerformed(evt);
            }
        });

        jlb_fk_cpf.setText("cpf do cliente:");

        jta_fk_cpf.setColumns(20);
        jta_fk_cpf.setRows(5);
        jScrollPane5.setViewportView(jta_fk_cpf);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbt_inserirPedido)
                        .addGap(18, 18, 18)
                        .addComponent(jbt_salvarPdfPedido)
                        .addGap(18, 18, 18)
                        .addComponent(jbt_salvarTxtPedido)
                        .addGap(18, 18, 18)
                        .addComponent(jbt_atualizarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbt_deletarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlb_id_pedido)
                            .addComponent(jScrollPane1)
                            .addComponent(jlb_dataPedido)
                            .addComponent(jScrollPane3)
                            .addComponent(jlb_prazoEntrega)
                            .addComponent(jScrollPane4)
                            .addComponent(jlb_fk_cpf)
                            .addComponent(jScrollPane5))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbt_atualizarPedido)
                            .addComponent(jbt_deletarPedido)
                            .addComponent(jbt_salvarTxtPedido)
                            .addComponent(jbt_salvarPdfPedido)
                            .addComponent(jbt_inserirPedido)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlb_id_pedido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlb_dataPedido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlb_prazoEntrega)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jlb_fk_cpf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbt_salvarPdfPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_salvarPdfPedidoActionPerformed
        // TODO add your handling code here:
        Document documento = new Document();
        PdfPTable pdft_tabela = new PdfPTable(4);
        listaPedido = pd_operacoes.buscarListaCompleta_pedido();
        for (Pedido p : listaPedido) 
        {
            
            pdft_tabela.addCell(String.valueOf(p.getId_pedido()));
            pdft_tabela.addCell(p.getFk_cpf());
            pdft_tabela.addCell(String.valueOf(p.getDataPedido()));
            pdft_tabela.addCell(String.valueOf(p.getPrazoEntrega()));
            
	}
        try {
            PdfWriter.getInstance(documento, new FileOutputStream("Relatorio_Tabela_Pedido.pdf"));
            documento.open();
            documento.add(new Paragraph(" "));
            documento.add(pdft_tabela);
            System.out.print("\n PDF criado com sucesso.");
            JOptionPane.showMessageDialog(null, "PDF criado com sucesso.");
        } catch (DocumentException | FileNotFoundException ex  ) {
            System.out.print("\n Erro: "+ex.toString());
        }
        documento.close();
    }//GEN-LAST:event_jbt_salvarPdfPedidoActionPerformed

    private void limpartela()
    {
        jta_id_pedido.setText("");
        jta_fk_cpf.setText("");
        jta_dataPedido.setText("");
        jta_prazoEntrega.setText("");
    }
    private void jbt_inserirPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_inserirPedidoActionPerformed
        // TODO add your handling code here:
        Pedido p = new Pedido();
        p.setId_pedido(Integer.parseInt(jta_id_pedido.getText()));
        p.setFk_cpf(jta_fk_cpf.getText());
        p.setDataPedido(LocalDateTime.parse(jta_dataPedido.getText()));
        p.setPrazoEntrega(Integer.parseInt(jta_prazoEntrega.getText()));
        pd_operacoes.adicionarPedido(p);
        
        limpartela();
        // Atualização da tabela para preservar a integridade do sistema.
        try {
            atualizaTabela();
        } catch (SQLException ex) {
            System.out.print("SQLException: "+ex.toString());
        } catch (ClassNotFoundException ex) {
            System.out.print("ClassNotFoundException: "+ex.toString());
        }
    }//GEN-LAST:event_jbt_inserirPedidoActionPerformed

    private void jbt_atualizarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_atualizarPedidoActionPerformed
        // TODO add your handling code here:
        Pedido p = new Pedido();
        p.setId_pedido(Integer.parseInt(jta_id_pedido.getText()));
        p.setFk_cpf(jta_fk_cpf.getText());
        p.setDataPedido(LocalDateTime.parse(jta_dataPedido.getText()));
        p.setPrazoEntrega(Integer.parseInt(jta_prazoEntrega.getText()));
        pd_operacoes.alterarPedido(p);
        
        limpartela();
        // Atualização da tabela para preservar a integridade do sistema.
        try {
            atualizaTabela();
        } catch (SQLException ex) {
            System.out.print("SQLException: "+ex.toString());
        } catch (ClassNotFoundException ex) {
            System.out.print("ClassNotFoundException: "+ex.toString());
        }
    }//GEN-LAST:event_jbt_atualizarPedidoActionPerformed

    private void jbt_deletarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_deletarPedidoActionPerformed
        // TODO add your handling code here:
        pd_operacoes.removerPedido(Integer.parseInt(jta_id_pedido.getText()));
        limpartela();
        
      try {
            atualizaTabela();
        } catch (SQLException ex) {
            System.out.print("SQLException: "+ex.toString());
        } catch (ClassNotFoundException ex) {
            System.out.print("ClassNotFoundException: "+ex.toString());
        }
     
    }//GEN-LAST:event_jbt_deletarPedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Pedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton jbt_atualizarPedido;
    private javax.swing.JButton jbt_deletarPedido;
    private javax.swing.JButton jbt_inserirPedido;
    private javax.swing.JButton jbt_salvarPdfPedido;
    private javax.swing.JButton jbt_salvarTxtPedido;
    private javax.swing.JLabel jlb_dataPedido;
    private javax.swing.JLabel jlb_fk_cpf;
    private javax.swing.JLabel jlb_id_pedido;
    private javax.swing.JLabel jlb_prazoEntrega;
    private javax.swing.JTextArea jta_dataPedido;
    private javax.swing.JTextArea jta_fk_cpf;
    private javax.swing.JTextArea jta_id_pedido;
    private javax.swing.JTextArea jta_prazoEntrega;
    private javax.swing.JTable jtb_pedido;
    // End of variables declaration//GEN-END:variables
}
