/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;
import dao.PerfumeDAO;
import bean.Perfume;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;

/**
 *
 * @author Duduzada
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    
    DefaultTableModel dtm_tabela;
    ArrayList <Perfume> listaPerfume;
    PerfumeDAO pd_operacoes;
    public Tela() {
        initComponents();
        //configuração tabela 
        dtm_tabela = new DefaultTableModel(null, new String[]{"id","volume","lote","tipo","venda","cor"});
        
        try {
            pd_operacoes = new PerfumeDAO();
        } catch (SQLException | ClassNotFoundException ex) {
            System.out.println("\n Erro ao conectar: "+ex.toString());
        }
        
        // Atualização da tabela para preservar a integridade do sistema.
        try {
            atualizaTabela();
        } catch (SQLException ex) {
            System.out.print("SQLException: "+ex.toString());
        } catch (ClassNotFoundException ex) {
            System.out.print("ClassNotFoundException: "+ex.toString());
        }
        //configuração para o volume
        jcmbox_volume.removeAllItems();
        jcmbox_volume.addItem("           ");
        jcmbox_volume.addItem("100ml");
        jcmbox_volume.addItem("200ml");
        jcmbox_volume.addItem("300ml");
        jcmbox_volume.addItem("400ml");
        //configuração para o combo box do tipo de perfume
        jcmbox_tipoDoPerfume.removeAllItems();
        jcmbox_tipoDoPerfume.addItem("           ");
        jcmbox_tipoDoPerfume.addItem("Amadeirado");
        jcmbox_tipoDoPerfume.addItem("Floral");
        jcmbox_tipoDoPerfume.addItem("Cheiroso");
        //configuração para a cor do perfume
        jcmbox_corDoLiquido.addItem("           ");
        jcmbox_corDoLiquido.addItem("Incolor");
        jcmbox_corDoLiquido.addItem("Marrom");
        jcmbox_corDoLiquido.addItem("Verde");
        
    }
    private void atualizaTabela() throws SQLException, ClassNotFoundException
    {
        jtb_perfume.setModel(dtm_tabela);
        dtm_tabela.setNumRows(0);
        listaPerfume = pd_operacoes.buscarListaCompleta_perfume();
        for (Perfume p : listaPerfume) 
        {
            dtm_tabela.addRow(new Object[]{p.getId_perfume(),p.getVolume(),p.getLote(),p.getTipoDoPerfume(),p.getValorVenda(),p.getCorDoLiquido()});
	}
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jFrame1 = new javax.swing.JFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtb_perfume = new javax.swing.JTable();
        jlb_id_perfume = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jta_id_perfume = new javax.swing.JTextArea();
        jlb_volume = new javax.swing.JLabel();
        jlb_lote = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jta_lote = new javax.swing.JTextArea();
        jlb_tipoDoPerfume = new javax.swing.JLabel();
        jcmbox_tipoDoPerfume = new javax.swing.JComboBox<>();
        jcmbox_volume = new javax.swing.JComboBox<>();
        jlb_valorVenda = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jta_valorVenda = new javax.swing.JTextArea();
        jlb_corDoLiquido = new javax.swing.JLabel();
        jbt_inserirPerfume = new javax.swing.JButton();
        jbt_salvarPdfPerfume = new javax.swing.JButton();
        jbt_salvarTxtPerfume = new javax.swing.JButton();
        jbt_atualizarPerfume = new javax.swing.JButton();
        jbt_deletarPerfume = new javax.swing.JButton();
        jcmbox_corDoLiquido = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmenu_perfume = new javax.swing.JMenu();
        jmenu_cliente = new javax.swing.JMenu();
        jmi_cliente = new javax.swing.JMenuItem();
        jmenu_pedido = new javax.swing.JMenu();
        jmi_pedido = new javax.swing.JMenuItem();
        menu_pedidop = new javax.swing.JMenu();
        jmi_pedidoPerfume = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem4.setText("jMenuItem4");

        jMenuItem5.setText("jMenuItem5");

        jMenuItem6.setText("jMenuItem6");

        jMenuItem7.setText("jMenuItem7");

        jMenuItem8.setText("jMenuItem8");

        jMenuItem9.setText("jMenuItem9");

        jMenuItem10.setText("jMenuItem10");

        jMenuItem11.setText("jMenuItem11");

        jMenuItem12.setText("jMenuItem12");

        jMenuItem13.setText("jMenuItem13");

        jMenuItem14.setText("jMenuItem14");

        jMenuItem15.setText("jMenuItem15");

        jMenu2.setText("jMenu2");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtb_perfume.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jtb_perfume);

        jlb_id_perfume.setText("identificador do perfume:");

        jta_id_perfume.setColumns(20);
        jta_id_perfume.setRows(5);
        jScrollPane3.setViewportView(jta_id_perfume);

        jlb_volume.setText("volume:");

        jlb_lote.setText("lote");

        jta_lote.setColumns(20);
        jta_lote.setRows(5);
        jScrollPane4.setViewportView(jta_lote);

        jlb_tipoDoPerfume.setText("tipo do perfume:");

        jcmbox_tipoDoPerfume.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcmbox_tipoDoPerfume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbox_tipoDoPerfumeActionPerformed(evt);
            }
        });

        jcmbox_volume.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcmbox_volume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbox_volumeActionPerformed(evt);
            }
        });

        jlb_valorVenda.setText("valor da venda:");

        jta_valorVenda.setColumns(20);
        jta_valorVenda.setRows(5);
        jScrollPane1.setViewportView(jta_valorVenda);

        jlb_corDoLiquido.setText("cor do liquido");

        jbt_inserirPerfume.setText("Inserir");
        jbt_inserirPerfume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_inserirPerfumeActionPerformed(evt);
            }
        });

        jbt_salvarPdfPerfume.setText("Salvar em PDF");
        jbt_salvarPdfPerfume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_salvarPdfPerfumeActionPerformed(evt);
            }
        });

        jbt_salvarTxtPerfume.setText("Salvar em TXT");

        jbt_atualizarPerfume.setText("Atualizar");
        jbt_atualizarPerfume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_atualizarPerfumeActionPerformed(evt);
            }
        });

        jbt_deletarPerfume.setText("Deletar");
        jbt_deletarPerfume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_deletarPerfumeActionPerformed(evt);
            }
        });

        jmenu_perfume.setText("Perfume");
        jMenuBar1.add(jmenu_perfume);

        jmenu_cliente.setText("Cliente");
        jmenu_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenu_clienteActionPerformed(evt);
            }
        });

        jmi_cliente.setText("Página Cliente");
        jmi_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_clienteActionPerformed(evt);
            }
        });
        jmenu_cliente.add(jmi_cliente);

        jMenuBar1.add(jmenu_cliente);

        jmenu_pedido.setText("Pedido");
        jmenu_pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenu_pedidoActionPerformed(evt);
            }
        });

        jmi_pedido.setText("Página Pedido");
        jmi_pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_pedidoActionPerformed(evt);
            }
        });
        jmenu_pedido.add(jmi_pedido);

        jMenuBar1.add(jmenu_pedido);

        menu_pedidop.setText("Pedido de Perfume");
        menu_pedidop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_pedidopActionPerformed(evt);
            }
        });

        jmi_pedidoPerfume.setText("Página Pedido de Perfume");
        jmi_pedidoPerfume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_pedidoPerfumeActionPerformed(evt);
            }
        });
        menu_pedidop.add(jmi_pedidoPerfume);

        jMenuBar1.add(menu_pedidop);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3)
                                    .addComponent(jScrollPane4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jlb_id_perfume)
                                            .addComponent(jlb_lote))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jlb_volume)
                                            .addComponent(jcmbox_volume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jcmbox_tipoDoPerfume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jlb_tipoDoPerfume))))
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlb_valorVenda)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlb_corDoLiquido))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(311, 311, 311)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbt_deletarPerfume, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbt_inserirPerfume, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbt_salvarPdfPerfume, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbt_salvarTxtPerfume, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jcmbox_corDoLiquido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbt_atualizarPerfume)
                        .addGap(155, 155, 155))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlb_id_perfume)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jlb_volume)
                                    .addComponent(jlb_tipoDoPerfume))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jcmbox_volume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcmbox_tipoDoPerfume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlb_lote)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlb_valorVenda)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlb_corDoLiquido))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcmbox_corDoLiquido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbt_atualizarPerfume))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbt_salvarTxtPerfume)
                    .addComponent(jbt_inserirPerfume))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbt_salvarPdfPerfume)
                    .addComponent(jbt_deletarPerfume))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //FUNÇÕES 
    private void limpartela()
    {
        jta_id_perfume.setText("");
        jcmbox_volume.equals("     ");
        jta_lote.setText("");
        jcmbox_tipoDoPerfume.equals("     ");
        jta_valorVenda.setText("");
        jcmbox_corDoLiquido.setSelectedItem("           ");
    }
    
    
    private void menu_pedidopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_pedidopActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_menu_pedidopActionPerformed

    private void jmenu_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenu_clienteActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jmenu_clienteActionPerformed

    private void jmenu_pedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenu_pedidoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jmenu_pedidoActionPerformed
    
    private void jcmbox_volumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbox_volumeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcmbox_volumeActionPerformed

    private void jcmbox_tipoDoPerfumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbox_tipoDoPerfumeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcmbox_tipoDoPerfumeActionPerformed

    private void jmi_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_clienteActionPerformed
        // TODO add your handling code here:
        Tela_Cliente tela_cliente = new Tela_Cliente();
        tela_cliente.setVisible(true);
    }//GEN-LAST:event_jmi_clienteActionPerformed

    private void jmi_pedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_pedidoActionPerformed
        // TODO add your handling code here:
        Tela_Pedido tela_pedido = new Tela_Pedido();
        tela_pedido.setVisible(true);
    }//GEN-LAST:event_jmi_pedidoActionPerformed

    private void jmi_pedidoPerfumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_pedidoPerfumeActionPerformed
        // TODO add your handling code here:
        Tela_PedidoPerfume tela_pedidoc = new Tela_PedidoPerfume();
        tela_pedidoc.setVisible(true);
    }//GEN-LAST:event_jmi_pedidoPerfumeActionPerformed

    private void jbt_inserirPerfumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_inserirPerfumeActionPerformed
        // TODO add your handling code here:
        Perfume c = new Perfume();
        c.setId_perfume(Integer.parseInt(jta_id_perfume.getText())); 
        c.setVolume(Float.parseFloat(jcmbox_volume.getSelectedItem().toString()));
        c.setLote(Float.parseFloat(jta_lote.getText()));
        c.setTipoDoPerfume(jcmbox_tipoDoPerfume.getSelectedItem().toString());
        c.setValorVenda(Float.parseFloat(jta_valorVenda.getText()));
        c.setCorDoLiquido(jcmbox_corDoLiquido.getSelectedItem().toString());
        pd_operacoes.adicionarPerfume(c);
        limpartela();
        // Atualização da tabela para preservar a integridade do sistema.
        try {
            atualizaTabela();
        } catch (SQLException ex) {
            System.out.print("SQLException: "+ex.toString());
        } catch (ClassNotFoundException ex) {
            System.out.print("ClassNotFoundException: "+ex.toString());
        }
        
    }//GEN-LAST:event_jbt_inserirPerfumeActionPerformed

    private void jbt_atualizarPerfumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_atualizarPerfumeActionPerformed
        // TODO add your handling code here:
                Perfume c = new Perfume();
        c.setId_perfume(Integer.parseInt(jta_id_perfume.getText())); 
        c.setVolume(Float.parseFloat(jcmbox_volume.getSelectedItem().toString()));
        c.setLote(Float.parseFloat(jta_lote.getText()));
        c.setTipoDoPerfume(jcmbox_tipoDoPerfume.getSelectedItem().toString());
        c.setValorVenda(Float.parseFloat(jta_valorVenda.getText()));
        c.setCorDoLiquido(jcmbox_corDoLiquido.getSelectedItem().toString());
        pd_operacoes.alterarPerfume(c);
        limpartela();
        // Atualização da tabela para preservar a integridade do sistema.
        try {
            atualizaTabela();
        } catch (SQLException ex) {
            System.out.print("SQLException: "+ex.toString());
        } catch (ClassNotFoundException ex) {
            System.out.print("ClassNotFoundException: "+ex.toString());
        }
    }//GEN-LAST:event_jbt_atualizarPerfumeActionPerformed

    private void jbt_deletarPerfumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_deletarPerfumeActionPerformed
        // TODO add your handling code here:
        pd_operacoes.removerPerfume(Integer.parseInt(jta_id_perfume.getText()));
        limpartela();
        
      try {
            atualizaTabela();
        } catch (SQLException ex) {
            System.out.print("SQLException: "+ex.toString());
        } catch (ClassNotFoundException ex) {
            System.out.print("ClassNotFoundException: "+ex.toString());
        }
    }//GEN-LAST:event_jbt_deletarPerfumeActionPerformed

    private void jbt_salvarPdfPerfumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_salvarPdfPerfumeActionPerformed
        // TODO add your handling code here:
        Document documento = new Document();
        PdfPTable pdft_tabela = new PdfPTable(7);
        listaPerfume = pd_operacoes.buscarListaCompleta_perfume();
        for (Perfume p : listaPerfume) 
        {
            
            pdft_tabela.addCell(String.valueOf(p.getId_perfume()));
            pdft_tabela.addCell(String.valueOf(p.getVolume()));
            pdft_tabela.addCell(String.valueOf(p.getLote()));
            pdft_tabela.addCell(p.getTipoDoPerfume());
            pdft_tabela.addCell(String.valueOf(p.getValorVenda()));
            pdft_tabela.addCell(String.valueOf(p.getCorDoLiquido()));
            
	}
        try {
            PdfWriter.getInstance(documento, new FileOutputStream("Relatorio_Tabela_Perfumes.pdf"));
            documento.open();
            documento.add(new Paragraph(" "));
            documento.add(pdft_tabela);
            System.out.print("\n PDF criado com sucesso.");
            JOptionPane.showMessageDialog(null, "PDF criado com sucesso.");
        } catch (DocumentException | FileNotFoundException ex  ) {
            System.out.print("\n Erro: "+ex.toString());
        }
        documento.close();
    }//GEN-LAST:event_jbt_salvarPdfPerfumeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame jFrame1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton jbt_atualizarPerfume;
    private javax.swing.JButton jbt_deletarPerfume;
    private javax.swing.JButton jbt_inserirPerfume;
    private javax.swing.JButton jbt_salvarPdfPerfume;
    private javax.swing.JButton jbt_salvarTxtPerfume;
    private javax.swing.JComboBox<String> jcmbox_corDoLiquido;
    private javax.swing.JComboBox<String> jcmbox_tipoDoPerfume;
    private javax.swing.JComboBox<String> jcmbox_volume;
    private javax.swing.JLabel jlb_corDoLiquido;
    private javax.swing.JLabel jlb_id_perfume;
    private javax.swing.JLabel jlb_lote;
    private javax.swing.JLabel jlb_tipoDoPerfume;
    private javax.swing.JLabel jlb_valorVenda;
    private javax.swing.JLabel jlb_volume;
    private javax.swing.JMenu jmenu_cliente;
    private javax.swing.JMenu jmenu_pedido;
    private javax.swing.JMenu jmenu_perfume;
    private javax.swing.JMenuItem jmi_cliente;
    private javax.swing.JMenuItem jmi_pedido;
    private javax.swing.JMenuItem jmi_pedidoPerfume;
    private javax.swing.JTextArea jta_id_perfume;
    private javax.swing.JTextArea jta_lote;
    private javax.swing.JTextArea jta_valorVenda;
    private javax.swing.JTable jtb_perfume;
    private javax.swing.JMenu menu_pedidop;
    // End of variables declaration//GEN-END:variables
}
