/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import bean.Pedido;
import bean.PedidoPerfume;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import dao.PedidoPerfumeDAO;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Duduzada
 */
public class Tela_PedidoPerfume extends javax.swing.JFrame {

    /**
     * Creates new form Tela_PedidoPerfume
     */
    DefaultTableModel dtm_tabela;
    ArrayList <PedidoPerfume> listaPedidoP;
    PedidoPerfumeDAO pd_operacoes;
    public Tela_PedidoPerfume() {
        initComponents();
        //configuração tabela 
        dtm_tabela = new DefaultTableModel(null, new String[]{"id","id pedido","id perfume","quantidade"});
        
        try {
            pd_operacoes = new PedidoPerfumeDAO();
        } catch (SQLException | ClassNotFoundException ex) {
            System.out.println("\n Erro ao conectar: "+ex.toString());
        }
        
        // Atualização da tabela para preservar a integridade do sistema.
        try {
            atualizaTabela();
        } catch (SQLException ex) {
            System.out.print("SQLException: "+ex.toString());
        } catch (ClassNotFoundException ex) {
            System.out.print("ClassNotFoundException: "+ex.toString());
        }
    }
    private void atualizaTabela() throws SQLException, ClassNotFoundException
    {
        jtb_pedidoPerfume.setModel(dtm_tabela);
        dtm_tabela.setNumRows(0);
        listaPedidoP = pd_operacoes.buscarListaCompleta_pedidoPerfume();
        for (PedidoPerfume p : listaPedidoP) 
        {
            dtm_tabela.addRow(new Object[]{p.getId_pedido_perfume(),p.getFk_id_pedido(),p.getFk_id_perfume(),p.getQuantidade()});
	}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlb_id_pedido_perfume = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jta_id_pedido_perfume = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtb_pedidoPerfume = new javax.swing.JTable();
        jlb_quantidade = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jta_quantidade = new javax.swing.JTextArea();
        jbt_salvarPdf_pedidoPerfume = new javax.swing.JButton();
        jbt_salvarTxt_pedidoPerfume = new javax.swing.JButton();
        jbt_inserirPedidoPerfume = new javax.swing.JButton();
        jbt_atualizarPedidoPerfume = new javax.swing.JButton();
        jbt_deletarPedidoPerfume = new javax.swing.JButton();
        jlb_fk_id_pedido = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jta_fk_id_pedido = new javax.swing.JTextArea();
        jlb_fk_id_perfume = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jta_fk_id_perfume = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jlb_id_pedido_perfume.setText("indentificador do pedido perfume:");

        jta_id_pedido_perfume.setColumns(20);
        jta_id_pedido_perfume.setRows(5);
        jScrollPane1.setViewportView(jta_id_pedido_perfume);

        jtb_pedidoPerfume.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jtb_pedidoPerfume);

        jlb_quantidade.setText("quantidade:");

        jta_quantidade.setColumns(20);
        jta_quantidade.setRows(5);
        jScrollPane3.setViewportView(jta_quantidade);

        jbt_salvarPdf_pedidoPerfume.setText("Salvar em PDF");
        jbt_salvarPdf_pedidoPerfume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_salvarPdf_pedidoPerfumeActionPerformed(evt);
            }
        });

        jbt_salvarTxt_pedidoPerfume.setText("Salvar em TXT");

        jbt_inserirPedidoPerfume.setText("Inserir");
        jbt_inserirPedidoPerfume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_inserirPedidoPerfumeActionPerformed(evt);
            }
        });

        jbt_atualizarPedidoPerfume.setText("Atualizar");
        jbt_atualizarPedidoPerfume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_atualizarPedidoPerfumeActionPerformed(evt);
            }
        });

        jbt_deletarPedidoPerfume.setText("Deletar");
        jbt_deletarPedidoPerfume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_deletarPedidoPerfumeActionPerformed(evt);
            }
        });

        jlb_fk_id_pedido.setText("indentificador do pedido:");

        jta_fk_id_pedido.setColumns(20);
        jta_fk_id_pedido.setRows(5);
        jScrollPane4.setViewportView(jta_fk_id_pedido);

        jlb_fk_id_perfume.setText("indentificador do perfume:");

        jta_fk_id_perfume.setColumns(20);
        jta_fk_id_perfume.setRows(5);
        jScrollPane5.setViewportView(jta_fk_id_perfume);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlb_id_pedido_perfume)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlb_quantidade)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlb_fk_id_pedido)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlb_fk_id_perfume)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbt_inserirPedidoPerfume)
                        .addGap(31, 31, 31)
                        .addComponent(jbt_salvarPdf_pedidoPerfume)
                        .addGap(37, 37, 37)
                        .addComponent(jbt_salvarTxt_pedidoPerfume)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbt_atualizarPedidoPerfume)
                        .addGap(43, 43, 43)
                        .addComponent(jbt_deletarPedidoPerfume)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlb_id_pedido_perfume)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlb_quantidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlb_fk_id_pedido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlb_fk_id_perfume)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbt_salvarTxt_pedidoPerfume)
                    .addComponent(jbt_atualizarPedidoPerfume)
                    .addComponent(jbt_deletarPedidoPerfume)
                    .addComponent(jbt_salvarPdf_pedidoPerfume)
                    .addComponent(jbt_inserirPedidoPerfume))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limpartela()
    {
        jta_id_pedido_perfume.setText("");
        jta_fk_id_pedido.setText("");
        jta_fk_id_perfume.setText("");
        jta_quantidade.setText("");
    }
    private void jbt_inserirPedidoPerfumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_inserirPedidoPerfumeActionPerformed
        // TODO add your handling code here:
        PedidoPerfume p = new PedidoPerfume();
        p.setId_pedido_perfume(Integer.parseInt(jta_id_pedido_perfume.getText()));
        p.setFk_id_pedido(Integer.parseInt(jta_fk_id_pedido.getText()));
        p.setFk_id_perfume(Integer.parseInt(jta_fk_id_perfume.getText()));
        p.setQuantidade(Integer.parseInt(jta_quantidade.getText()));
        pd_operacoes.adicionarPedidoPerfume(p);
        
        limpartela();
        // Atualização da tabela para preservar a integridade do sistema.
        try {
            atualizaTabela();
        } catch (SQLException ex) {
            System.out.print("SQLException: "+ex.toString());
        } catch (ClassNotFoundException ex) {
            System.out.print("ClassNotFoundException: "+ex.toString());
        }
    }//GEN-LAST:event_jbt_inserirPedidoPerfumeActionPerformed

    private void jbt_atualizarPedidoPerfumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_atualizarPedidoPerfumeActionPerformed
        // TODO add your handling code here:
        PedidoPerfume p = new PedidoPerfume();
        p.setId_pedido_perfume(Integer.parseInt(jta_id_pedido_perfume.getText()));
        p.setFk_id_pedido(Integer.parseInt(jta_fk_id_pedido.getText()));
        p.setFk_id_perfume(Integer.parseInt(jta_fk_id_perfume.getText()));
        p.setQuantidade(Integer.parseInt(jta_quantidade.getText()));
        pd_operacoes.alterarPedidoPerfume(p);
        
        limpartela();
        // Atualização da tabela para preservar a integridade do sistema.
        try {
            atualizaTabela();
        } catch (SQLException ex) {
            System.out.print("SQLException: "+ex.toString());
        } catch (ClassNotFoundException ex) {
            System.out.print("ClassNotFoundException: "+ex.toString());
        }
    }//GEN-LAST:event_jbt_atualizarPedidoPerfumeActionPerformed

    private void jbt_deletarPedidoPerfumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_deletarPedidoPerfumeActionPerformed
        // TODO add your handling code here:
        pd_operacoes.removerPedidoPerfume(Integer.parseInt(jta_id_pedido_perfume.getText()));
        limpartela();
        
      try {
            atualizaTabela();
        } catch (SQLException ex) {
            System.out.print("SQLException: "+ex.toString());
        } catch (ClassNotFoundException ex) {
            System.out.print("ClassNotFoundException: "+ex.toString());
        }
    }//GEN-LAST:event_jbt_deletarPedidoPerfumeActionPerformed

    private void jbt_salvarPdf_pedidoPerfumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_salvarPdf_pedidoPerfumeActionPerformed
        // TODO add your handling code here:
        Document documento = new Document();
        PdfPTable pdft_tabela = new PdfPTable(4);
        listaPedidoP = pd_operacoes.buscarListaCompleta_pedidoPerfume();
        for (PedidoPerfume p : listaPedidoP) 
        {
            
            pdft_tabela.addCell(String.valueOf(p.getId_pedido_perfume()));
            pdft_tabela.addCell(String.valueOf(p.getFk_id_pedido()));
            pdft_tabela.addCell(String.valueOf(p.getFk_id_perfume()));
            pdft_tabela.addCell(String.valueOf(p.getQuantidade()));
            
	}
        try {
            PdfWriter.getInstance(documento, new FileOutputStream("Relatorio_Tabela_Pedido_Perfume.pdf"));
            documento.open();
            documento.add(new Paragraph(" "));
            documento.add(pdft_tabela);
            System.out.print("\n PDF criado com sucesso.");
            JOptionPane.showMessageDialog(null, "PDF criado com sucesso.");
        } catch (DocumentException | FileNotFoundException ex  ) {
            System.out.print("\n Erro: "+ex.toString());
        }
        documento.close();
    }//GEN-LAST:event_jbt_salvarPdf_pedidoPerfumeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_PedidoPerfume.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_PedidoPerfume.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_PedidoPerfume.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_PedidoPerfume.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_PedidoPerfume().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton jbt_atualizarPedidoPerfume;
    private javax.swing.JButton jbt_deletarPedidoPerfume;
    private javax.swing.JButton jbt_inserirPedidoPerfume;
    private javax.swing.JButton jbt_salvarPdf_pedidoPerfume;
    private javax.swing.JButton jbt_salvarTxt_pedidoPerfume;
    private javax.swing.JLabel jlb_fk_id_pedido;
    private javax.swing.JLabel jlb_fk_id_perfume;
    private javax.swing.JLabel jlb_id_pedido_perfume;
    private javax.swing.JLabel jlb_quantidade;
    private javax.swing.JTextArea jta_fk_id_pedido;
    private javax.swing.JTextArea jta_fk_id_perfume;
    private javax.swing.JTextArea jta_id_pedido_perfume;
    private javax.swing.JTextArea jta_quantidade;
    private javax.swing.JTable jtb_pedidoPerfume;
    // End of variables declaration//GEN-END:variables
}
